opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_enum_arguments
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - legacy_random
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - reduce_into
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - strong_iboutlet
  - trailing_newline
  - type_name
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules

disabled_rules:
  - identifier_name
  
colon:
  apply_to_dictionaries: false

indentation: 2

line_length:
  error: 120

type_body_length:
  warning: 400

function_body_length:
  warning: 40
  
